<?php
session_start();
include "../connection.php";
require_once('../TCPDF-main/TCPDF-main/tcpdf.php');
if (!isset($_SESSION['admin_id']) || !isset($_GET['form_id'])) {
    exit('Access denied');
}

$form_id = intval($_GET['form_id']);

// Fetch form data
$form = mysqli_fetch_assoc(mysqli_query($con, "SELECT sf.*, u.username FROM student_forms sf JOIN user u ON u.id = sf.user_id WHERE sf.id = $form_id"));
if (!$form) exit('Form not found');

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('NCCS College');
$pdf->SetTitle('Student Application Form');
$pdf->SetMargins(15, 20, 15);
$pdf->AddPage();

// Header: College name
$pdf->SetFont('helvetica', 'B', 20);
$pdf->Cell(0, 10, 'NCCS College', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 14);
$pdf->Cell(0, 8, 'Student Application Form', 0, 1, 'C');
$pdf->Ln(5);

// Add student photo (top-right)
// Original file path from DB
// Add student photo (top-right)
$original_file = '../uploads/' . $form['file_path']; // adjust path
$img_for_pdf = $original_file;

if (file_exists($original_file)) {
    $ext = strtolower(pathinfo($original_file, PATHINFO_EXTENSION));
    if ($ext === 'png') {
        // Convert PNG to JPEG
        $jpg_file = '../uploads/tmp_' . pathinfo($original_file, PATHINFO_FILENAME) . '.jpg';
        $image = imagecreatefrompng($original_file);
        imagejpeg($image, $jpg_file, 90); // quality 90
        imagedestroy($image);
        $img_for_pdf = $jpg_file;
    }

    $pdf_width = 40; // width of image
    $x_pos = $pdf->GetPageWidth() - $pdf_width - 15; // 15mm right margin
    $pdf->Image($img_for_pdf, $x_pos, 25, $pdf_width, 50); // Y=25mm, W=40mm, H=50mm
}



$pdf->Ln(60);

// Personal Details
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 8, 'Personal Details', 0, 1);
$pdf->SetFont('helvetica', '', 12);

$personal = [
    'First Name' => $form['fname'],
    'Last Name' => $form['lname'],
    'Date of Birth' => $form['dob'],
    'Contact Number' => $form['contact_number'],
    'Gender' => $form['gender'],
    'Email' => $form['email'],
];

foreach ($personal as $label => $value) {
    $pdf->Cell(50, 8, $label . ':', 0, 0);
    $pdf->Cell(0, 8, $value ?: '-', 0, 1);
}

$pdf->Ln(5);

// Academic Details
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 8, 'Academic Details', 0, 1);
$pdf->SetFont('helvetica', '', 12);

$academic = [
    'School Name' => $form['school_name'],
    'SEE GPA' => $form['see_gpa'],
    'College Name' => $form['college_name'],
    '+2 GPA' => $form['plus2_gpa'],
    'IOST Marks' => $form['iost_marks'],
    'Faculty Applied' => $form['faculty'],
];

foreach ($academic as $label => $value) {
    $pdf->Cell(50, 8, $label . ':', 0, 0);
    $pdf->Cell(0, 8, $value ?: '-', 0, 1);
}

$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'Application Status: ' . strtoupper($form['status']), 0, 1);

$pdf->Ln(10);
$pdf->SetFont('helvetica', 'I', 10);
$pdf->Cell(0, 8, 'Generated by NCCS College Admin Panel', 0, 1, 'C');

// Output PDF
$pdf->Output('application_form_' . $form['id'] . '.pdf', 'I');
